# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import chunkserver_pb2 as chunkserver__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in chunkserver_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChunkServerServiceStub(object):
    """Client <-> Chunk Server communication

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WriteChunk = channel.stream_unary(
                '/dfs.ChunkServerService/WriteChunk',
                request_serializer=chunkserver__pb2.WriteChunkRequest.SerializeToString,
                response_deserializer=chunkserver__pb2.WriteChunkResponse.FromString,
                _registered_method=True)
        self.ReadChunk = channel.unary_stream(
                '/dfs.ChunkServerService/ReadChunk',
                request_serializer=chunkserver__pb2.ReadChunkRequest.SerializeToString,
                response_deserializer=chunkserver__pb2.ReadChunkResponse.FromString,
                _registered_method=True)


class ChunkServerServiceServicer(object):
    """Client <-> Chunk Server communication

    """

    def WriteChunk(self, request_iterator, context):
        """Client streams chunk data to the chunk server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadChunk(self, request, context):
        """Client requests a chunk, chunk server streams it back
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChunkServerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WriteChunk': grpc.stream_unary_rpc_method_handler(
                    servicer.WriteChunk,
                    request_deserializer=chunkserver__pb2.WriteChunkRequest.FromString,
                    response_serializer=chunkserver__pb2.WriteChunkResponse.SerializeToString,
            ),
            'ReadChunk': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadChunk,
                    request_deserializer=chunkserver__pb2.ReadChunkRequest.FromString,
                    response_serializer=chunkserver__pb2.ReadChunkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dfs.ChunkServerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dfs.ChunkServerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChunkServerService(object):
    """Client <-> Chunk Server communication

    """

    @staticmethod
    def WriteChunk(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/dfs.ChunkServerService/WriteChunk',
            chunkserver__pb2.WriteChunkRequest.SerializeToString,
            chunkserver__pb2.WriteChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dfs.ChunkServerService/ReadChunk',
            chunkserver__pb2.ReadChunkRequest.SerializeToString,
            chunkserver__pb2.ReadChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
