# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chunkserver.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'chunkserver.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63hunkserver.proto\x12\x03\x64\x66s\"R\n\x11WriteChunkRequest\x12\x14\n\x0c\x63hunk_handle\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x19\n\x11\x66orward_addresses\x18\x03 \x03(\t\"6\n\x12WriteChunkResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"(\n\x10ReadChunkRequest\x12\x14\n\x0c\x63hunk_handle\x18\x01 \x01(\t\"!\n\x11ReadChunkResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\x93\x01\n\x12\x43hunkServerService\x12?\n\nWriteChunk\x12\x16.dfs.WriteChunkRequest\x1a\x17.dfs.WriteChunkResponse(\x01\x12<\n\tReadChunk\x12\x15.dfs.ReadChunkRequest\x1a\x16.dfs.ReadChunkResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chunkserver_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WRITECHUNKREQUEST']._serialized_start=26
  _globals['_WRITECHUNKREQUEST']._serialized_end=108
  _globals['_WRITECHUNKRESPONSE']._serialized_start=110
  _globals['_WRITECHUNKRESPONSE']._serialized_end=164
  _globals['_READCHUNKREQUEST']._serialized_start=166
  _globals['_READCHUNKREQUEST']._serialized_end=206
  _globals['_READCHUNKRESPONSE']._serialized_start=208
  _globals['_READCHUNKRESPONSE']._serialized_end=241
  _globals['_CHUNKSERVERSERVICE']._serialized_start=244
  _globals['_CHUNKSERVERSERVICE']._serialized_end=391
# @@protoc_insertion_point(module_scope)
