# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import heartbeat_pb2 as heartbeat__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in heartbeat_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HeartbeatServiceStub(object):
    """Master <-> Chunk Server internal communication

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Heartbeat = channel.unary_unary(
                '/dfs.HeartbeatService/Heartbeat',
                request_serializer=heartbeat__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=heartbeat__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.ReplicateChunk = channel.unary_unary(
                '/dfs.HeartbeatService/ReplicateChunk',
                request_serializer=heartbeat__pb2.ReplicateChunkRequest.SerializeToString,
                response_deserializer=heartbeat__pb2.ReplicateChunkResponse.FromString,
                _registered_method=True)
        self.SearchChunks = channel.unary_unary(
                '/dfs.HeartbeatService/SearchChunks',
                request_serializer=heartbeat__pb2.SearchChunksRequest.SerializeToString,
                response_deserializer=heartbeat__pb2.SearchChunksResponse.FromString,
                _registered_method=True)


class HeartbeatServiceServicer(object):
    """Master <-> Chunk Server internal communication

    """

    def Heartbeat(self, request, context):
        """Chunk server sends periodic heartbeat to master
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicateChunk(self, request, context):
        """Master tells chunk server to copy a chunk from another server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchChunks(self, request, context):
        """Master forwards a search query to a chunk server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HeartbeatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=heartbeat__pb2.HeartbeatRequest.FromString,
                    response_serializer=heartbeat__pb2.HeartbeatResponse.SerializeToString,
            ),
            'ReplicateChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicateChunk,
                    request_deserializer=heartbeat__pb2.ReplicateChunkRequest.FromString,
                    response_serializer=heartbeat__pb2.ReplicateChunkResponse.SerializeToString,
            ),
            'SearchChunks': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchChunks,
                    request_deserializer=heartbeat__pb2.SearchChunksRequest.FromString,
                    response_serializer=heartbeat__pb2.SearchChunksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dfs.HeartbeatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dfs.HeartbeatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HeartbeatService(object):
    """Master <-> Chunk Server internal communication

    """

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfs.HeartbeatService/Heartbeat',
            heartbeat__pb2.HeartbeatRequest.SerializeToString,
            heartbeat__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplicateChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfs.HeartbeatService/ReplicateChunk',
            heartbeat__pb2.ReplicateChunkRequest.SerializeToString,
            heartbeat__pb2.ReplicateChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchChunks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfs.HeartbeatService/SearchChunks',
            heartbeat__pb2.SearchChunksRequest.SerializeToString,
            heartbeat__pb2.SearchChunksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
