# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: heartbeat.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'heartbeat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fheartbeat.proto\x12\x03\x64\x66s\"T\n\x10HeartbeatRequest\x12\x11\n\tserver_id\x18\x01 \x01(\x05\x12\x16\n\x0e\x61vailable_disk\x18\x02 \x01(\x03\x12\x15\n\rchunk_handles\x18\x03 \x03(\t\"$\n\x11HeartbeatResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"E\n\x15ReplicateChunkRequest\x12\x14\n\x0c\x63hunk_handle\x18\x01 \x01(\t\x12\x16\n\x0esource_address\x18\x02 \x01(\t\":\n\x16ReplicateChunkResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"$\n\x13SearchChunksRequest\x12\r\n\x05query\x18\x01 \x01(\t\"W\n\nChunkMatch\x12\x14\n\x0c\x63hunk_handle\x18\x01 \x01(\t\x12\x13\n\x0bline_number\x18\x02 \x01(\x05\x12\r\n\x05score\x18\x03 \x01(\x02\x12\x0f\n\x07snippet\x18\x04 \x01(\t\"8\n\x14SearchChunksResponse\x12 \n\x07matches\x18\x01 \x03(\x0b\x32\x0f.dfs.ChunkMatch2\xde\x01\n\x10HeartbeatService\x12:\n\tHeartbeat\x12\x15.dfs.HeartbeatRequest\x1a\x16.dfs.HeartbeatResponse\x12I\n\x0eReplicateChunk\x12\x1a.dfs.ReplicateChunkRequest\x1a\x1b.dfs.ReplicateChunkResponse\x12\x43\n\x0cSearchChunks\x12\x18.dfs.SearchChunksRequest\x1a\x19.dfs.SearchChunksResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'heartbeat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEARTBEATREQUEST']._serialized_start=24
  _globals['_HEARTBEATREQUEST']._serialized_end=108
  _globals['_HEARTBEATRESPONSE']._serialized_start=110
  _globals['_HEARTBEATRESPONSE']._serialized_end=146
  _globals['_REPLICATECHUNKREQUEST']._serialized_start=148
  _globals['_REPLICATECHUNKREQUEST']._serialized_end=217
  _globals['_REPLICATECHUNKRESPONSE']._serialized_start=219
  _globals['_REPLICATECHUNKRESPONSE']._serialized_end=277
  _globals['_SEARCHCHUNKSREQUEST']._serialized_start=279
  _globals['_SEARCHCHUNKSREQUEST']._serialized_end=315
  _globals['_CHUNKMATCH']._serialized_start=317
  _globals['_CHUNKMATCH']._serialized_end=404
  _globals['_SEARCHCHUNKSRESPONSE']._serialized_start=406
  _globals['_SEARCHCHUNKSRESPONSE']._serialized_end=462
  _globals['_HEARTBEATSERVICE']._serialized_start=465
  _globals['_HEARTBEATSERVICE']._serialized_end=687
# @@protoc_insertion_point(module_scope)
